---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-secret
  namespace: default
spec:
  encryptedData:
    PG_PASSWORD: AgB7KaonuswIHdLKIQp9CRRT3dmoT1M7oRDCPyj4/65cbovWJ7o+QEYjMlfM0bjvhu1niBtQPviLwI6KcocxMRudlAvrMrHdrF/mVN3ZlM8NyMgfCi9QQEcP/YjO2NsBJCPW4ABr3bCEg5bHwmMIjiwytvSlhWxCgIFdvwIIni2eIUIEyE2beis31Y+UmGLv+/lXKT/y53em6MRFa6cP/4G2PWyfN3K/+lCfsv1FADZ9c3A2eFeyQ6SZDiEhHGJE7IhyxyYN19Y/5LxlwFV+bm+3hs9Bb/q2MwIbY6Rd4jyDqZcgrNZ9xqoYQRt9AlqEDHxcB7PX1LCC5yk30yqcBoP6WlPbu2j8X4hV3vt6Mizd1O0SyG0+IjZeH7Q6HQDJ4ju2sqyt7IhBsaYKD/DcAluG30A4MG2YH/532qmBPXUtFgTLm4fKJY5bAjZ3Ej6sz7eI3CV6/TCgyRU34NUrPp/HJA0jpobk937JenBPYQNAFOljo/6Q6v15+WKLzLvpKwU7T5Ir4YD6SKYXZNliJ2AwjF2UPbMktV1INfbn1Oghb5JLHWJ8L1tgd1xokdgOqC63zsyw5T3NZkcG5iC8u5x2cKG/U8nJBgyO6KUoa4Wufyyyqfgk/3hE1huN+wr9aOFprZ9cBt6BJXXcoJae8omJvBq9+zXOtI4CUpl9K/NYUSAmO//PxiRSni3d7JNJ2WrG8m9Dpu+6HEtq34Os6GIR6eE2PyVDWCCN9Sd6duhaCEgiDpV+kZnB9f93hA==
  template:
    metadata:
      name: postgres-secret
      namespace: default