apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  labels:
    pv-label: postgres
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /pv-data/pg-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: hostname
              operator: In
              values: ["worker-vm1"]
