apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  labels:
    pvc-label: postgres
spec:
  selector:
    matchLabels:
      pv-label: postgres
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
