apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  annotations:
    argocd.argoproj.io/sync-options: SkipDiff
type: opaque
stringData:
  PG_PASSWORD: ${{ secrets.DB_PASSWORD }} # from github secrets
