name: release

on:
  push:
    branches: ["main"]

jobs:
  linting:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Fetch all branches
        run: git fetch --all

      - name: Set Working_dir
        run: echo "WORKING_DIR=$(pwd)" >> $GITHUB_ENV

      - name: Yaml Lint
        uses: ./.github/actions/yaml-lint
        with:
          repo_dir: $WORKING_DIR

  security:
    runs-on: ubuntu-latest
    needs: linting
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/iac@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor

  validation:
    runs-on: self-hosted
    needs: security
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45

      - name: List all changed files
        env:
          CHD_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for file in ${CHD_FILES}; do
            [[ "$file" == *".github/"* ]] && continue
            echo "$file was changed"
          done

      - name: Kubectl Diff
        env:
          CHD_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        if: ${{ steps.changed-files.outputs.all_changed_files != '' }}
        run: |
          for file in ${CHD_FILES}; do
            [[ "$file" == *".github/"* ]] && continue
            echo "Running KUBECTL diff on $file"
            kubectl diff -f "$file" || true
          done

      - name: Kubectl Dry Run
        env:
          CHD_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        if: ${{ steps.changed-files.outputs.all_changed_files != '' }}
        run: |
          for file in ${CHD_FILES}; do
            [[ "$file" == *".github/"* ]] && continue
            echo "Running KUBECTL dry-run on $file"
            kubectl apply --dry-run=server -f "$file" || true
          done

  apply:
    runs-on: self-hosted
    needs: validation
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45

      - name: Kubectl Apply
        env:
          CHD_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        if: ${{ steps.changed-files.outputs.all_changed_files != '' }}
        run: |
          for file in ${CHD_FILES}; do
            [[ "$file" == *".github/"* ]] && continue
            echo "Running KUBECTL dry-run on $file"
            kubectl apply -f "$file" || true
          done
